---
  - name: Install apache
    hosts: all
    gather_facts: yes
    tasks:
      - name: Install apache on centos7
        when:
          - ansible_facts['distribution'] == "CentOS"
          - ansible_facts['distributionmajor_version'] == "7"
        yum: 
          name: 
          - httpd
          state: latest
        register: apache_installed
      - name: start apache
        when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
        - apache_installed is success
        systemd:
          state: started
          name: httpd
          enabled: yes
      - name: Install apache on Ubuntu
        when: 
        - ansible_facts['distribution'] == "Ubuntu"
        apt:
          name:
          - apache2
          state: latest
        register: apache_installed_ubuntu
      - name: start apache on ubuntu
        when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - apache_installed_ubuntu is success
        systemd:
          state: started
          name: apache2
          enabled: yes
