---
  - name:  install machine
  ##kimler olacak##
    hosts: localhost
      tasks:
        - name: Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            name: Enver
            oauth_token: 25ea8cb503975104ae0685f86b5025736553e6cf9d406c28050c909af741cfd3
            size: 1gb
            region: sfo1
            image: ubuntu-16-04-x64
            wait_timeout: 500
            ssh_keys: [ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIQlarL6f82MiVAnpe0+2DX2iMROu0GZIsrGxtDK3qu+p/vO1osJTeJSwh39Ap9RTzz+mdGIUDj4yPOd7PC2PHDz2vo7d3aLJ4yQ4adzuUli/IaAhg8W5i0yT6ECwMKK1BijZBMH02CSAlynhMAnz62n4JsfueMNnUXgGPBE5SjXBl3EpwBKqPWpExyrcUTLFA0368iGn2rRRbfvBy5c9NL4cWaLsGjhQwRF7A0OfO6KLlBXXE7/ExZev2Li5S1WhMHyT7819xVDgqoJ4fGVwJuCPCIcRZVwkFATGBOaeyI+DPMe2sar8yzCscldCZMHuwtooe41aRf6m3wHOOyD8/ root@MyAnsibleMachine]
          register: my_droplet